name: Trigger auto deployment for rec-engine

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/rec-engine-AutoDeployTrigger-f92fc66f-2682-4b1b-90a8-3071b3421fcf.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RECENGINE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RECENGINE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RECENGINE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/DockfileContainerApp 
          registryUrl: docker.io
          registryUsername: ${{ secrets.RECENGINE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RECENGINE_REGISTRY_PASSWORD }}
          containerAppName: rec-engine
          resourceGroup: test2-1
          imageToBuild: raychung/rec-engine:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


